/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiJobsIdDownloadRouteImport } from './routes/api/jobs/$id/download'
import { Route as ApiJobsIdThumbnailRouteImport } from './routes/api/jobs/$id/thumbnail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsIdDownloadRoute = ApiJobsIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiJobsIdRoute,
} as any)
const ApiJobsIdThumbnailRoute = ApiJobsIdThumbnailRouteImport.update({
  id: '/thumbnail',
  path: '/thumbnail',
  getParentRoute: () => ApiJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/download': typeof ApiJobsIdDownloadRoute
  '/api/jobs/$id/thumbnail': typeof ApiJobsIdThumbnailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/download': typeof ApiJobsIdDownloadRoute
  '/api/jobs/$id/thumbnail': typeof ApiJobsIdThumbnailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/download': typeof ApiJobsIdDownloadRoute
  '/api/jobs/$id/thumbnail': typeof ApiJobsIdThumbnailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/download'
    | '/api/jobs/$id/thumbnail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/download'
    | '/api/jobs/$id/thumbnail'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/download'
    | '/api/jobs/$id/thumbnail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$id/download': {
      id: '/api/jobs/$id/download'
      path: '/download'
      fullPath: '/api/jobs/$id/download'
      preLoaderRoute: typeof ApiJobsIdDownloadRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
    '/api/jobs/$id/thumbnail': {
      id: '/api/jobs/$id/thumbnail'
      path: '/thumbnail'
      fullPath: '/api/jobs/$id/thumbnail'
      preLoaderRoute: typeof ApiJobsIdThumbnailRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
  }
}

interface ApiJobsIdRouteChildren {
  ApiJobsIdDownloadRoute: typeof ApiJobsIdDownloadRoute
  ApiJobsIdThumbnailRoute: typeof ApiJobsIdThumbnailRoute
}

const ApiJobsIdRouteChildren: ApiJobsIdRouteChildren = {
  ApiJobsIdDownloadRoute: ApiJobsIdDownloadRoute,
  ApiJobsIdThumbnailRoute: ApiJobsIdThumbnailRoute,
}

const ApiJobsIdRouteWithChildren = ApiJobsIdRoute._addFileChildren(
  ApiJobsIdRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsIdRoute: typeof ApiJobsIdRouteWithChildren
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsIdRoute: ApiJobsIdRouteWithChildren,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
